name: "Huangsir"
markdown: kramdown
highlighter: pygments
permalink: :title
exclude: [README.md, LICENSE, Makefile]

# Information for the Atom feed
gereksiz:
   author: "Huangsir"
   email: "rj.huangsir@gmail.com"
   companyName: "Youmi"
   company: "http://www.youmi.net"
