# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: node:latest
      
    working_directory: ~/repo
    
    branches:
      only:
        - develop

    steps:
      - checkout
      - run: npm install acyort -g
      - run: git config --global user.email "rj.huangsir@gmail.com"
      - run: git config --global user.name "Huangsir"
      - run: git checkout master
      - run: git reset --hard origin/master
      - run: git checkout develop
      - run: git clone https://github.com/acyortjs/theme-donob.git themes/donob
      - run: acyort build
      - run: git checkout master
      - run: cp -R public/* .
      - run: rm -R public
      - run: ls -alh
      - run: git status
      - run: git add .
      - run: git commit -am "build by circleci - `date`"
      - run: git push origin master
